export const ActionTypes = {
    BLOG_CREATE: 'BLOG_CREATE',
    BLOG_CREATE_SUCCESS: 'BLOG_CREATE_SUCCESS',
    BLOG_CREATE_FAILURE: 'BLOG_CREATE_FAILURE',
    PUBLISH_REQUEST: 'PUBLISH_REQUEST',
    PUBLISH_SUCCESS: 'PUBLISH_SUCCESS',
    PUBLISH_FAILURE: 'PUBLISH_FAILURE',
    SOCIAL_MEDIA_REQUEST: 'SOCIAL_MEDIA_REQUEST',
    SOCIAL_MEDIA_SUCCESS: 'SOCIAL_MEDIA_SUCCESS',
    SOCIAL_MEDIA_FAILURE: 'SOCIAL_MEDIA_FAILURE',

    GET_SOCIAL_MEDIA_REQUEST: 'GET_SOCIAL_MEDIA_REQUEST',
    GET_SOCIAL_MEDIA_SUCCESS: 'GET_SOCIAL_MEDIA_SUCCESS',
    GET_SOCIAL_MEDIA_FAILURE: 'GET_SOCIAL_MEDIA_FAILURE'

}