export const ActionTypes = {
    BLOG_CREATE: 'BLOG_CREATE',
    BLOG_CREATE_SUCCESS: 'BLOG_CREATE_SUCCESS',
    BLOG_CREATE_FAILURE: 'BLOG_CREATE_FAILURE',
    PUBLISH_REQUEST: 'PUBLISH_REQUEST',
    PUBLISH_SUCCESS: 'PUBLISH_SUCCESS',
    PUBLISH_FAILURE: 'PUBLISH_FAILURE',
    GET_BLOG_LIST: 'GET_BLOG_LIST',
    GET_BLOG_LIST_SUCCESS: 'GET_BLOG_LIST_SUCCESS',
    GET_BLOG_LIST_FAILURE: 'GET_BLOG_LIST_FAILURE',
    SET_EDIT_BLOG: 'SET_EDIT_BLOG',
    DELETE_BLOG: 'DELETE_BLOG',
    DELETE_BLOG_SUCCESS: 'DELETE_BLOG_SUCCESS',
    DELETE_BLOG_FAILURE: 'DELETE_BLOG_FAILURE',
    EDIT_BLOG: 'EDIT_BLOG',
    EDIT_BLOG_SUCCESS: 'EDIT_BLOG_SUCCESS',
    EDIT_BLOG_FAILURE: 'EDIT_BLOG_FAILURE',
    CLONE_BLOG: 'CLONE_BLOG'
}
