export const ActionTypes = {
    BLOG_CREATE: 'BLOG_CREATE',
    BLOG_CREATE_SUCCESS: 'BLOG_CREATE_SUCCESS',
    BLOG_CREATE_FAILURE: 'BLOG_CREATE_FAILURE',
    PUBLISH_REQUEST: 'PUBLISH_REQUEST',
    PUBLISH_SUCCESS: 'PUBLISH_SUCCESS',
    PUBLISH_FAILURE: 'PUBLISH_FAILURE'
}
