export const ActionTypes = {
    GET_ASSESSMENT_REQUEST: 'GET_ASSESSMENT_REQUEST',
    GET_ASSESSMENT_SUCCESS: 'GET_ASSESSMENT_SUCCESS',
    GET_ASSESSMENT_FAILURE: 'GET_ASSESSMENT_FAILURE',

    CREATE_ASSESSMENT_REQUEST: 'CREATE_ASSESSMENT_REQUEST',
    CREATE_ASSESSMENT_SUCCESS: 'CREATE_ASSESSMENT_SUCCESS',
    CREATE_ASSESSMENT_FAILURE: 'CREATE_ASSESSMENT_FAILURE',

    GET_UNSPLASH_SUCCESS: 'GET_UNSPLASH_SUCCESS',
    GET_UNSPLASH_ERROR: 'GET_UNSPLASH_ERROR',
    GET_VERIFIED_DOMAIN: 'GET_VERIFIED_DOMAIN',

    CLEAR_DOMAINS: 'CLEAR_DOMAINS'

    
}
